services:
  cassandra_node1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042" #CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=TaskManagerCluster
      - CASSANDRA_NUM_TOKENS=12
      - CASSANDRA_SEEDS=cassandra-node2
    volumes:
      - "cassandra_data1:/var/lib/cassandra"
    networks:
      cassandra-network:
        aliases:
          - cassandra-node1
  cassandra_node2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9043:9042" #CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=TaskManagerCluster
      - CASSANDRA_NUM_TOKENS=12
      - CASSANDRA_SEEDS=cassandra-node1
    volumes:
      - "cassandra_data2:/var/lib/cassandra"
    networks:
      cassandra-network:
        aliases:
          - cassandra-node2
  cassandra_node3:
    image: cassandra:latest
    container_name: cassandra3
    ports:
      - "9044:9042" #CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=TaskManagerCluster
      - CASSANDRA_NUM_TOKENS=12
      - CASSANDRA_SEEDS=cassandra-node1
    volumes:
      - "cassandra_data3:/var/lib/cassandra"
    networks:
      cassandra-network:
        aliases:
          - cassandra-node3

volumes:
  cassandra_data1:
  cassandra_data2:
  cassandra_data3:

networks:
  cassandra-network:
    driver: bridge